### ISSUE TITLE
Troubleshooting with location of svg

### ISSUE THREAD

**Issue by ThomasIdgeo** [MrXsquared/OSM-Geofabrik_Universal-QML-Style#1]
Hi,
thanks too lot for this job !

it's not explain clearly about the add of the folder svg in the Preferences > option > system.

Also, the file ExampleProject.qgs try to find the svgs symbols in the subdirectory '15/'

If your are more quickly than us before our pull request ;-)

**Comment by MrXsquared** [comment]
Location of SVG should be fixed now. But location of SVG was always a pain because they automatically change to their absolute path instead of leaving it relative. In newer versions (I guess 3.4+) it would also be possible to embedd SVGs via base 64 encoding which would probably the better solution.
